title: Raster Analysis using Open-Source Python
description: A Tufts University Data Lab Workshop
repo: python-raster
author: Uku-Kaspar Uustalu
slides: python-raster
file: python-raster.ipynb
env: python-raster
